// Code generated by protoc-gen-go. DO NOT EDIT.
// source: root_coord.proto

package rootcoordpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/milvus-io/milvus/internal/proto/commonpb"
	datapb "github.com/milvus-io/milvus/internal/proto/datapb"
	etcdpb "github.com/milvus-io/milvus/internal/proto/etcdpb"
	internalpb "github.com/milvus-io/milvus/internal/proto/internalpb"
	milvuspb "github.com/milvus-io/milvus/internal/proto/milvuspb"
	proxypb "github.com/milvus-io/milvus/internal/proto/proxypb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AllocTimestampRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Count                uint32            `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AllocTimestampRequest) Reset()         { *m = AllocTimestampRequest{} }
func (m *AllocTimestampRequest) String() string { return proto.CompactTextString(m) }
func (*AllocTimestampRequest) ProtoMessage()    {}
func (*AllocTimestampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{0}
}

func (m *AllocTimestampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocTimestampRequest.Unmarshal(m, b)
}
func (m *AllocTimestampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocTimestampRequest.Marshal(b, m, deterministic)
}
func (m *AllocTimestampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocTimestampRequest.Merge(m, src)
}
func (m *AllocTimestampRequest) XXX_Size() int {
	return xxx_messageInfo_AllocTimestampRequest.Size(m)
}
func (m *AllocTimestampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocTimestampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllocTimestampRequest proto.InternalMessageInfo

func (m *AllocTimestampRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *AllocTimestampRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AllocTimestampResponse struct {
	Status               *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            uint64           `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Count                uint32           `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AllocTimestampResponse) Reset()         { *m = AllocTimestampResponse{} }
func (m *AllocTimestampResponse) String() string { return proto.CompactTextString(m) }
func (*AllocTimestampResponse) ProtoMessage()    {}
func (*AllocTimestampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{1}
}

func (m *AllocTimestampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocTimestampResponse.Unmarshal(m, b)
}
func (m *AllocTimestampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocTimestampResponse.Marshal(b, m, deterministic)
}
func (m *AllocTimestampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocTimestampResponse.Merge(m, src)
}
func (m *AllocTimestampResponse) XXX_Size() int {
	return xxx_messageInfo_AllocTimestampResponse.Size(m)
}
func (m *AllocTimestampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocTimestampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllocTimestampResponse proto.InternalMessageInfo

func (m *AllocTimestampResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AllocTimestampResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AllocTimestampResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AllocIDRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Count                uint32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AllocIDRequest) Reset()         { *m = AllocIDRequest{} }
func (m *AllocIDRequest) String() string { return proto.CompactTextString(m) }
func (*AllocIDRequest) ProtoMessage()    {}
func (*AllocIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{2}
}

func (m *AllocIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocIDRequest.Unmarshal(m, b)
}
func (m *AllocIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocIDRequest.Marshal(b, m, deterministic)
}
func (m *AllocIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocIDRequest.Merge(m, src)
}
func (m *AllocIDRequest) XXX_Size() int {
	return xxx_messageInfo_AllocIDRequest.Size(m)
}
func (m *AllocIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllocIDRequest proto.InternalMessageInfo

func (m *AllocIDRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *AllocIDRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AllocIDResponse struct {
	Status               *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ID                   int64            `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Count                uint32           `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AllocIDResponse) Reset()         { *m = AllocIDResponse{} }
func (m *AllocIDResponse) String() string { return proto.CompactTextString(m) }
func (*AllocIDResponse) ProtoMessage()    {}
func (*AllocIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{3}
}

func (m *AllocIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocIDResponse.Unmarshal(m, b)
}
func (m *AllocIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocIDResponse.Marshal(b, m, deterministic)
}
func (m *AllocIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocIDResponse.Merge(m, src)
}
func (m *AllocIDResponse) XXX_Size() int {
	return xxx_messageInfo_AllocIDResponse.Size(m)
}
func (m *AllocIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllocIDResponse proto.InternalMessageInfo

func (m *AllocIDResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AllocIDResponse) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AllocIDResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ImportResult struct {
	Status               *commonpb.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TaskId               int64                    `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State                commonpb.ImportState     `protobuf:"varint,3,opt,name=state,proto3,enum=milvus.proto.common.ImportState" json:"state,omitempty"`
	Segments             []int64                  `protobuf:"varint,4,rep,packed,name=segments,proto3" json:"segments,omitempty"`
	AutoIds              []int64                  `protobuf:"varint,5,rep,packed,name=auto_ids,json=autoIds,proto3" json:"auto_ids,omitempty"`
	RowCount             int64                    `protobuf:"varint,6,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	Infos                []*commonpb.KeyValuePair `protobuf:"bytes,7,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ImportResult) Reset()         { *m = ImportResult{} }
func (m *ImportResult) String() string { return proto.CompactTextString(m) }
func (*ImportResult) ProtoMessage()    {}
func (*ImportResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{4}
}

func (m *ImportResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportResult.Unmarshal(m, b)
}
func (m *ImportResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportResult.Marshal(b, m, deterministic)
}
func (m *ImportResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportResult.Merge(m, src)
}
func (m *ImportResult) XXX_Size() int {
	return xxx_messageInfo_ImportResult.Size(m)
}
func (m *ImportResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportResult.DiscardUnknown(m)
}

var xxx_messageInfo_ImportResult proto.InternalMessageInfo

func (m *ImportResult) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ImportResult) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *ImportResult) GetState() commonpb.ImportState {
	if m != nil {
		return m.State
	}
	return commonpb.ImportState_ImportPending
}

func (m *ImportResult) GetSegments() []int64 {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *ImportResult) GetAutoIds() []int64 {
	if m != nil {
		return m.AutoIds
	}
	return nil
}

func (m *ImportResult) GetRowCount() int64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *ImportResult) GetInfos() []*commonpb.KeyValuePair {
	if m != nil {
		return m.Infos
	}
	return nil
}

type DescribeSegmentsRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CollectionID         int64             `protobuf:"varint,2,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	SegmentIDs           []int64           `protobuf:"varint,3,rep,packed,name=segmentIDs,proto3" json:"segmentIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DescribeSegmentsRequest) Reset()         { *m = DescribeSegmentsRequest{} }
func (m *DescribeSegmentsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeSegmentsRequest) ProtoMessage()    {}
func (*DescribeSegmentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{5}
}

func (m *DescribeSegmentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeSegmentsRequest.Unmarshal(m, b)
}
func (m *DescribeSegmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeSegmentsRequest.Marshal(b, m, deterministic)
}
func (m *DescribeSegmentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeSegmentsRequest.Merge(m, src)
}
func (m *DescribeSegmentsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeSegmentsRequest.Size(m)
}
func (m *DescribeSegmentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeSegmentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeSegmentsRequest proto.InternalMessageInfo

func (m *DescribeSegmentsRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DescribeSegmentsRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *DescribeSegmentsRequest) GetSegmentIDs() []int64 {
	if m != nil {
		return m.SegmentIDs
	}
	return nil
}

type SegmentBaseInfo struct {
	CollectionID         int64    `protobuf:"varint,1,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64    `protobuf:"varint,2,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentBaseInfo) Reset()         { *m = SegmentBaseInfo{} }
func (m *SegmentBaseInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentBaseInfo) ProtoMessage()    {}
func (*SegmentBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{6}
}

func (m *SegmentBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentBaseInfo.Unmarshal(m, b)
}
func (m *SegmentBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentBaseInfo.Marshal(b, m, deterministic)
}
func (m *SegmentBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentBaseInfo.Merge(m, src)
}
func (m *SegmentBaseInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentBaseInfo.Size(m)
}
func (m *SegmentBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentBaseInfo proto.InternalMessageInfo

func (m *SegmentBaseInfo) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *SegmentBaseInfo) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

type SegmentInfos struct {
	BaseInfo             *SegmentBaseInfo            `protobuf:"bytes,1,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	IndexInfos           []*etcdpb.SegmentIndexInfo  `protobuf:"bytes,2,rep,name=index_infos,json=indexInfos,proto3" json:"index_infos,omitempty"`
	ExtraIndexInfos      map[int64]*etcdpb.IndexInfo `protobuf:"bytes,3,rep,name=extra_index_infos,json=extraIndexInfos,proto3" json:"extra_index_infos,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SegmentInfos) Reset()         { *m = SegmentInfos{} }
func (m *SegmentInfos) String() string { return proto.CompactTextString(m) }
func (*SegmentInfos) ProtoMessage()    {}
func (*SegmentInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{7}
}

func (m *SegmentInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentInfos.Unmarshal(m, b)
}
func (m *SegmentInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentInfos.Marshal(b, m, deterministic)
}
func (m *SegmentInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentInfos.Merge(m, src)
}
func (m *SegmentInfos) XXX_Size() int {
	return xxx_messageInfo_SegmentInfos.Size(m)
}
func (m *SegmentInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentInfos.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentInfos proto.InternalMessageInfo

func (m *SegmentInfos) GetBaseInfo() *SegmentBaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

func (m *SegmentInfos) GetIndexInfos() []*etcdpb.SegmentIndexInfo {
	if m != nil {
		return m.IndexInfos
	}
	return nil
}

func (m *SegmentInfos) GetExtraIndexInfos() map[int64]*etcdpb.IndexInfo {
	if m != nil {
		return m.ExtraIndexInfos
	}
	return nil
}

type DescribeSegmentsResponse struct {
	Status               *commonpb.Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CollectionID         int64                   `protobuf:"varint,2,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	SegmentInfos         map[int64]*SegmentInfos `protobuf:"bytes,3,rep,name=segment_infos,json=segmentInfos,proto3" json:"segment_infos,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DescribeSegmentsResponse) Reset()         { *m = DescribeSegmentsResponse{} }
func (m *DescribeSegmentsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeSegmentsResponse) ProtoMessage()    {}
func (*DescribeSegmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4513485a144f6b06, []int{8}
}

func (m *DescribeSegmentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeSegmentsResponse.Unmarshal(m, b)
}
func (m *DescribeSegmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeSegmentsResponse.Marshal(b, m, deterministic)
}
func (m *DescribeSegmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeSegmentsResponse.Merge(m, src)
}
func (m *DescribeSegmentsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeSegmentsResponse.Size(m)
}
func (m *DescribeSegmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeSegmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeSegmentsResponse proto.InternalMessageInfo

func (m *DescribeSegmentsResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeSegmentsResponse) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *DescribeSegmentsResponse) GetSegmentInfos() map[int64]*SegmentInfos {
	if m != nil {
		return m.SegmentInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*AllocTimestampRequest)(nil), "milvus.proto.rootcoord.AllocTimestampRequest")
	proto.RegisterType((*AllocTimestampResponse)(nil), "milvus.proto.rootcoord.AllocTimestampResponse")
	proto.RegisterType((*AllocIDRequest)(nil), "milvus.proto.rootcoord.AllocIDRequest")
	proto.RegisterType((*AllocIDResponse)(nil), "milvus.proto.rootcoord.AllocIDResponse")
	proto.RegisterType((*ImportResult)(nil), "milvus.proto.rootcoord.ImportResult")
	proto.RegisterType((*DescribeSegmentsRequest)(nil), "milvus.proto.rootcoord.DescribeSegmentsRequest")
	proto.RegisterType((*SegmentBaseInfo)(nil), "milvus.proto.rootcoord.SegmentBaseInfo")
	proto.RegisterType((*SegmentInfos)(nil), "milvus.proto.rootcoord.SegmentInfos")
	proto.RegisterMapType((map[int64]*etcdpb.IndexInfo)(nil), "milvus.proto.rootcoord.SegmentInfos.ExtraIndexInfosEntry")
	proto.RegisterType((*DescribeSegmentsResponse)(nil), "milvus.proto.rootcoord.DescribeSegmentsResponse")
	proto.RegisterMapType((map[int64]*SegmentInfos)(nil), "milvus.proto.rootcoord.DescribeSegmentsResponse.SegmentInfosEntry")
}

func init() { proto.RegisterFile("root_coord.proto", fileDescriptor_4513485a144f6b06) }

var fileDescriptor_4513485a144f6b06 = []byte{
	// 1266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xeb, 0x72, 0xda, 0x46,
	0x14, 0x36, 0xe0, 0xeb, 0x01, 0x83, 0xb3, 0x63, 0xc7, 0x94, 0x64, 0x3a, 0x84, 0xb6, 0x31, 0xce,
	0x05, 0x3c, 0x64, 0x26, 0x4d, 0xf3, 0xcf, 0x86, 0xd4, 0x61, 0x5a, 0xcf, 0x24, 0x22, 0xe9, 0x3d,
	0xa3, 0x2e, 0xd2, 0x09, 0xd6, 0x58, 0x68, 0xb1, 0x76, 0x89, 0xed, 0x9f, 0x7d, 0x82, 0x3e, 0x43,
	0x9f, 0xa5, 0x0f, 0xd0, 0x87, 0xe8, 0x8b, 0x74, 0x56, 0x37, 0x24, 0x21, 0x61, 0x39, 0xe9, 0x3f,
	0x76, 0xf5, 0xed, 0xf7, 0x9d, 0xf3, 0x9d, 0xbd, 0x02, 0x5b, 0x36, 0x63, 0x42, 0xd5, 0x18, 0xb3,
	0xf5, 0xd6, 0xc4, 0x66, 0x82, 0x91, 0xdb, 0x63, 0xc3, 0xfc, 0x30, 0xe5, 0x6e, 0xab, 0x25, 0x3f,
	0x3b, 0x5f, 0x6b, 0x25, 0x8d, 0x8d, 0xc7, 0xcc, 0x72, 0xfb, 0x6b, 0xa5, 0x30, 0xaa, 0x56, 0x36,
	0x2c, 0x81, 0xb6, 0x45, 0x4d, 0xaf, 0x5d, 0x9c, 0xd8, 0xec, 0xf2, 0xca, 0x6b, 0x6c, 0xe9, 0x54,
	0xd0, 0xb0, 0x44, 0xad, 0x82, 0x42, 0xd3, 0xd5, 0x31, 0x0a, 0xea, 0x76, 0x34, 0x54, 0xd8, 0x39,
	0x34, 0x4d, 0xa6, 0xbd, 0x31, 0xc6, 0xc8, 0x05, 0x1d, 0x4f, 0x14, 0x3c, 0x9f, 0x22, 0x17, 0xe4,
	0x00, 0x96, 0x87, 0x94, 0x63, 0x35, 0x57, 0xcf, 0x35, 0x8b, 0x9d, 0xbb, 0xad, 0x48, 0x6c, 0x5e,
	0x40, 0x27, 0x7c, 0x74, 0x44, 0x39, 0x2a, 0x0e, 0x92, 0x6c, 0xc3, 0x8a, 0xc6, 0xa6, 0x96, 0xa8,
	0x16, 0xea, 0xb9, 0xe6, 0xa6, 0xe2, 0x36, 0x1a, 0x7f, 0xe4, 0xe0, 0x76, 0x5c, 0x81, 0x4f, 0x98,
	0xc5, 0x91, 0x3c, 0x81, 0x55, 0x2e, 0xa8, 0x98, 0x72, 0x4f, 0xe4, 0x4e, 0xa2, 0xc8, 0xc0, 0x81,
	0x28, 0x1e, 0x94, 0xdc, 0x85, 0x0d, 0xe1, 0x33, 0x55, 0xf3, 0xf5, 0x5c, 0x73, 0x59, 0x99, 0x75,
	0xa4, 0xc4, 0xf0, 0x13, 0x94, 0x9d, 0x10, 0xfa, 0xbd, 0xff, 0x21, 0xbb, 0x7c, 0x98, 0xd9, 0x84,
	0x4a, 0xc0, 0xfc, 0x29, 0x59, 0x95, 0x21, 0xdf, 0xef, 0x39, 0xd4, 0x05, 0x25, 0xdf, 0xef, 0xa5,
	0xe4, 0xf1, 0x57, 0x1e, 0x4a, 0xfd, 0xf1, 0x84, 0xd9, 0x42, 0x41, 0x3e, 0x35, 0xc5, 0xc7, 0x69,
	0xed, 0xc2, 0x9a, 0xa0, 0xfc, 0x4c, 0x35, 0x74, 0x4f, 0x70, 0x55, 0x36, 0xfb, 0x3a, 0x79, 0x0a,
	0x2b, 0x12, 0x82, 0x8e, 0x68, 0xb9, 0x53, 0x4f, 0x24, 0x73, 0xf5, 0x25, 0x25, 0x2a, 0x2e, 0x9c,
	0xd4, 0x60, 0x9d, 0xe3, 0x68, 0x8c, 0x96, 0xe0, 0xd5, 0xe5, 0x7a, 0xa1, 0x59, 0x50, 0x82, 0x36,
	0xf9, 0x0c, 0xd6, 0xe9, 0x54, 0x30, 0xd5, 0xd0, 0x79, 0x75, 0xc5, 0xf9, 0xb6, 0x26, 0xdb, 0x7d,
	0x9d, 0x93, 0x3b, 0xb0, 0x61, 0xb3, 0x0b, 0xd5, 0xcd, 0x73, 0xd5, 0x89, 0x64, 0xdd, 0x66, 0x17,
	0x5d, 0xd9, 0x26, 0x5f, 0xc3, 0x8a, 0x61, 0xbd, 0x67, 0xbc, 0xba, 0x56, 0x2f, 0x34, 0x8b, 0x9d,
	0x7b, 0x89, 0xb1, 0x7c, 0x87, 0x57, 0x3f, 0x50, 0x73, 0x8a, 0xaf, 0xa8, 0x61, 0x2b, 0x2e, 0xbe,
	0xf1, 0x67, 0x0e, 0x76, 0x7b, 0xc8, 0x35, 0xdb, 0x18, 0xe2, 0xc0, 0x8b, 0xe2, 0xe3, 0xab, 0xde,
	0x80, 0x92, 0xc6, 0x4c, 0x13, 0x35, 0x61, 0x30, 0x2b, 0xa8, 0x50, 0xa4, 0x8f, 0x7c, 0x0e, 0xe0,
	0xa5, 0xdb, 0xef, 0xf1, 0x6a, 0xc1, 0x49, 0x32, 0xd4, 0xd3, 0xf8, 0x11, 0x2a, 0x5e, 0x20, 0x92,
	0xb8, 0x6f, 0xbd, 0x67, 0x73, 0xb4, 0xb9, 0x04, 0xda, 0x3a, 0x14, 0x27, 0xd4, 0x16, 0x46, 0x44,
	0x39, 0xdc, 0xd5, 0xf8, 0x37, 0x0f, 0x25, 0x8f, 0x59, 0xb2, 0x72, 0xd2, 0x83, 0x0d, 0x19, 0xb5,
	0x2a, 0x9d, 0xf0, 0x92, 0xdc, 0x6b, 0x25, 0x6f, 0x2a, 0xad, 0x58, 0x48, 0xca, 0xfa, 0xd0, 0x0f,
	0xae, 0x07, 0x45, 0xc3, 0xd2, 0xf1, 0x52, 0x75, 0x0b, 0x90, 0x77, 0x0a, 0xf0, 0x45, 0x94, 0x47,
	0x6e, 0x23, 0xad, 0x40, 0x5b, 0xc7, 0x4b, 0x87, 0x03, 0x0c, 0xff, 0x27, 0x27, 0x08, 0xb7, 0xf0,
	0x52, 0xd8, 0x54, 0x0d, 0x73, 0x15, 0x1c, 0xae, 0x6f, 0xae, 0x89, 0xc9, 0x21, 0x68, 0xbd, 0x90,
	0xa3, 0x03, 0x6e, 0xfe, 0xc2, 0x12, 0xf6, 0x95, 0x52, 0xc1, 0x68, 0x6f, 0xed, 0x77, 0xd8, 0x4e,
	0x02, 0x92, 0x2d, 0x28, 0x9c, 0xe1, 0x95, 0x67, 0xac, 0xfc, 0x49, 0x3a, 0xb0, 0xf2, 0x41, 0x4e,
	0x16, 0xc7, 0xc9, 0xb9, 0xea, 0x3b, 0x09, 0xcd, 0x32, 0x71, 0xa1, 0xcf, 0xf3, 0xcf, 0x72, 0x8d,
	0xbf, 0xf3, 0x50, 0x9d, 0x9f, 0x50, 0x9f, 0xb2, 0xd8, 0xb3, 0x4c, 0xaa, 0x11, 0x6c, 0x7a, 0x53,
	0x28, 0x62, 0xdd, 0x51, 0x9a, 0x75, 0x69, 0x11, 0x46, 0x3c, 0x75, 0x3d, 0x2c, 0xf1, 0x50, 0x57,
	0x0d, 0xe1, 0xd6, 0x1c, 0x24, 0xc1, 0xbd, 0xe7, 0x51, 0xf7, 0xbe, 0xcc, 0x52, 0xc2, 0x90, 0x8b,
	0x9d, 0x7f, 0x76, 0x61, 0x43, 0x61, 0x4c, 0x74, 0x25, 0x8a, 0x4c, 0x80, 0x1c, 0xa3, 0xe8, 0xb2,
	0xf1, 0x84, 0x59, 0x68, 0xb9, 0xbb, 0x09, 0x27, 0x07, 0x51, 0xd2, 0xe0, 0x64, 0x9b, 0x87, 0x7a,
	0x0b, 0xba, 0x76, 0x3f, 0x65, 0x44, 0x0c, 0xde, 0x58, 0x22, 0x63, 0x47, 0x51, 0x9e, 0x41, 0x6f,
	0x0c, 0xed, 0xac, 0x7b, 0x4a, 0x2d, 0x0b, 0xcd, 0x45, 0x8a, 0x31, 0xa8, 0xaf, 0x18, 0x5b, 0x07,
	0x5e, 0x63, 0x20, 0x6c, 0xc3, 0x1a, 0xf9, 0x9e, 0x37, 0x96, 0xc8, 0x39, 0x6c, 0x1f, 0xa3, 0xa3,
	0x6e, 0x70, 0x61, 0x68, 0xdc, 0x17, 0xec, 0xa4, 0x0b, 0xce, 0x81, 0x6f, 0x28, 0xa9, 0xc2, 0x56,
	0xd7, 0x46, 0x2a, 0xb0, 0x1b, 0xcc, 0x23, 0xf2, 0x28, 0x71, 0x68, 0x1c, 0xe6, 0x0b, 0x2d, 0x9a,
	0xbc, 0x8d, 0x25, 0xf2, 0x2b, 0x94, 0x7b, 0x36, 0x9b, 0x84, 0xe8, 0x1f, 0x24, 0xd2, 0x47, 0x41,
	0x19, 0xc9, 0x55, 0xd8, 0x7c, 0x49, 0x79, 0x88, 0x7b, 0x3f, 0x91, 0x3b, 0x82, 0xf1, 0xa9, 0xef,
	0x25, 0x42, 0x8f, 0x18, 0x33, 0x43, 0xf6, 0x5c, 0x00, 0xf1, 0xd7, 0x48, 0x48, 0xa5, 0x95, 0x9c,
	0xc1, 0x1c, 0xd0, 0x97, 0x6a, 0x67, 0xc6, 0x07, 0xc2, 0x6f, 0xa1, 0xe8, 0x1a, 0x7e, 0x68, 0x1a,
	0x94, 0x93, 0xbd, 0x05, 0x25, 0x71, 0x10, 0x19, 0x0d, 0x7b, 0x0d, 0x1b, 0xd2, 0x68, 0x97, 0xf4,
	0xab, 0xd4, 0x42, 0xdc, 0x84, 0x72, 0x00, 0x70, 0x68, 0x0a, 0xb4, 0x5d, 0xce, 0xfb, 0x89, 0x9c,
	0x33, 0x40, 0x46, 0x52, 0x0b, 0x2a, 0x83, 0x53, 0x79, 0xaa, 0xfb, 0xd6, 0x70, 0xf2, 0x30, 0x79,
	0x42, 0x47, 0x51, 0x3e, 0xfd, 0xa3, 0x6c, 0xe0, 0xc0, 0xee, 0x77, 0x50, 0x71, 0xcd, 0x7c, 0xe5,
	0x9f, 0x94, 0x29, 0x7a, 0x31, 0x54, 0xc6, 0x74, 0x7e, 0x86, 0x4d, 0x69, 0xeb, 0x8c, 0x7c, 0x3f,
	0xd5, 0xfa, 0x9b, 0x52, 0xbf, 0x83, 0xd2, 0x4b, 0xca, 0x67, 0xcc, 0xcd, 0xb4, 0x15, 0x30, 0x47,
	0x9c, 0x69, 0x01, 0x9c, 0x41, 0x59, 0xba, 0x16, 0x0c, 0xe6, 0x29, 0xcb, 0x37, 0x0a, 0xf2, 0x25,
	0x1e, 0x66, 0xc2, 0x06, 0x62, 0x16, 0x54, 0x62, 0x27, 0x52, 0x4a, 0x15, 0x62, 0xa8, 0xc5, 0x55,
	0x9f, 0x03, 0x07, 0x7a, 0x08, 0x25, 0x19, 0x8b, 0x7f, 0xfa, 0xa5, 0x78, 0x17, 0x86, 0xf8, 0x4a,
	0xfb, 0x19, 0x90, 0xa1, 0x4d, 0x64, 0x2b, 0x7e, 0xd0, 0x92, 0x76, 0xf6, 0x23, 0xd9, 0x55, 0x3c,
	0xb8, 0xe9, 0x19, 0x1e, 0xde, 0x44, 0x9c, 0x2b, 0xca, 0xc2, 0x4d, 0xc4, 0x41, 0x64, 0x9c, 0x72,
	0xa7, 0xb0, 0xe9, 0x8b, 0xba, 0xc4, 0xfb, 0x0b, 0x7d, 0x8f, 0x50, 0x3f, 0xc8, 0x02, 0x0d, 0x12,
	0xf0, 0xb6, 0x2b, 0x57, 0x25, 0x7d, 0xbb, 0xba, 0x49, 0xf0, 0xe7, 0xde, 0xab, 0x2e, 0x78, 0x58,
	0x92, 0xc7, 0x69, 0xce, 0x26, 0x3e, 0x71, 0x6b, 0xad, 0xac, 0xf0, 0x20, 0x8b, 0xdf, 0x60, 0xcd,
	0x7b, 0xee, 0xc5, 0xb7, 0xc7, 0xd8, 0xe0, 0xe0, 0xa5, 0x59, 0xdb, 0xbb, 0x16, 0x17, 0xb0, 0x53,
	0xd8, 0x79, 0x3b, 0xd1, 0xe5, 0xd1, 0xec, 0x5e, 0x00, 0xfc, 0x2b, 0x48, 0xbc, 0x2a, 0xb3, 0x6b,
	0x4e, 0x14, 0x77, 0xc2, 0x47, 0xd7, 0x79, 0x66, 0xc2, 0xae, 0x82, 0x26, 0x52, 0x8e, 0xbd, 0xd7,
	0xdf, 0x9f, 0x20, 0xe7, 0x74, 0x84, 0x03, 0x61, 0x23, 0x1d, 0xc7, 0xaf, 0x26, 0xee, 0xff, 0x08,
	0x29, 0xe0, 0x8c, 0x15, 0xd2, 0x60, 0xc7, 0x9b, 0xcb, 0xdf, 0x9a, 0x53, 0x7e, 0x2a, 0x6f, 0x65,
	0x26, 0x0a, 0xd4, 0xe3, 0x7b, 0x81, 0x4e, 0x05, 0x6d, 0x25, 0x22, 0x33, 0xa4, 0xa4, 0x02, 0x1c,
	0xa3, 0x38, 0x41, 0x61, 0x1b, 0x5a, 0xda, 0xa9, 0x35, 0x03, 0xa4, 0x94, 0x25, 0x01, 0x17, 0x94,
	0x65, 0x00, 0xab, 0xee, 0xa3, 0x97, 0x34, 0x12, 0x07, 0xf9, 0x2f, 0xf2, 0x45, 0xb7, 0xb5, 0xe0,
	0xd5, 0x1e, 0xda, 0x8d, 0x8f, 0x51, 0x84, 0x1e, 0xd3, 0x29, 0xbb, 0x71, 0x14, 0xb4, 0x78, 0x37,
	0x8e, 0x63, 0x43, 0x19, 0x94, 0x14, 0x94, 0x1f, 0xbc, 0x3c, 0x52, 0x6f, 0xef, 0xe1, 0x3f, 0x17,
	0xae, 0xf1, 0xfd, 0xe8, 0xd9, 0x2f, 0x4f, 0x47, 0x86, 0x38, 0x9d, 0x0e, 0xe5, 0x97, 0xb6, 0x0b,
	0x7d, 0x6c, 0x30, 0xef, 0x57, 0xdb, 0x9f, 0xa4, 0x6d, 0x67, 0x74, 0x3b, 0xd0, 0x98, 0x0c, 0x87,
	0xab, 0x4e, 0xd7, 0x93, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x22, 0xe4, 0x68, 0x97, 0x02, 0x13,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RootCoordClient is the client API for RootCoord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RootCoordClient interface {
	GetComponentStates(ctx context.Context, in *internalpb.GetComponentStatesRequest, opts ...grpc.CallOption) (*internalpb.ComponentStates, error)
	GetTimeTickChannel(ctx context.Context, in *internalpb.GetTimeTickChannelRequest, opts ...grpc.CallOption) (*milvuspb.StringResponse, error)
	GetStatisticsChannel(ctx context.Context, in *internalpb.GetStatisticsChannelRequest, opts ...grpc.CallOption) (*milvuspb.StringResponse, error)
	//*
	// @brief This method is used to create collection
	//
	// @param CreateCollectionRequest, use to provide collection information to be created.
	//
	// @return Status
	CreateCollection(ctx context.Context, in *milvuspb.CreateCollectionRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	//*
	// @brief This method is used to delete collection.
	//
	// @param DropCollectionRequest, collection name is going to be deleted.
	//
	// @return Status
	DropCollection(ctx context.Context, in *milvuspb.DropCollectionRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	//*
	// @brief This method is used to test collection existence.
	//
	// @param HasCollectionRequest, collection name is going to be tested.
	//
	// @return BoolResponse
	HasCollection(ctx context.Context, in *milvuspb.HasCollectionRequest, opts ...grpc.CallOption) (*milvuspb.BoolResponse, error)
	//*
	// @brief This method is used to get collection schema.
	//
	// @param DescribeCollectionRequest, target collection name.
	//
	// @return CollectionSchema
	DescribeCollection(ctx context.Context, in *milvuspb.DescribeCollectionRequest, opts ...grpc.CallOption) (*milvuspb.DescribeCollectionResponse, error)
	CreateAlias(ctx context.Context, in *milvuspb.CreateAliasRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	DropAlias(ctx context.Context, in *milvuspb.DropAliasRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	AlterAlias(ctx context.Context, in *milvuspb.AlterAliasRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	//*
	// @brief This method is used to list all collections.
	//
	// @return StringListResponse, collection name list
	ShowCollections(ctx context.Context, in *milvuspb.ShowCollectionsRequest, opts ...grpc.CallOption) (*milvuspb.ShowCollectionsResponse, error)
	//*
	// @brief This method is used to create partition
	//
	// @return Status
	CreatePartition(ctx context.Context, in *milvuspb.CreatePartitionRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	//*
	// @brief This method is used to drop partition
	//
	// @return Status
	DropPartition(ctx context.Context, in *milvuspb.DropPartitionRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	//*
	// @brief This method is used to test partition existence.
	//
	// @return BoolResponse
	HasPartition(ctx context.Context, in *milvuspb.HasPartitionRequest, opts ...grpc.CallOption) (*milvuspb.BoolResponse, error)
	//*
	// @brief This method is used to show partition information
	//
	// @param ShowPartitionRequest, target collection name.
	//
	// @return StringListResponse
	ShowPartitions(ctx context.Context, in *milvuspb.ShowPartitionsRequest, opts ...grpc.CallOption) (*milvuspb.ShowPartitionsResponse, error)
	DescribeSegment(ctx context.Context, in *milvuspb.DescribeSegmentRequest, opts ...grpc.CallOption) (*milvuspb.DescribeSegmentResponse, error)
	ShowSegments(ctx context.Context, in *milvuspb.ShowSegmentsRequest, opts ...grpc.CallOption) (*milvuspb.ShowSegmentsResponse, error)
	DescribeSegments(ctx context.Context, in *DescribeSegmentsRequest, opts ...grpc.CallOption) (*DescribeSegmentsResponse, error)
	CreateIndex(ctx context.Context, in *milvuspb.CreateIndexRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	DescribeIndex(ctx context.Context, in *milvuspb.DescribeIndexRequest, opts ...grpc.CallOption) (*milvuspb.DescribeIndexResponse, error)
	DropIndex(ctx context.Context, in *milvuspb.DropIndexRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	AllocTimestamp(ctx context.Context, in *AllocTimestampRequest, opts ...grpc.CallOption) (*AllocTimestampResponse, error)
	AllocID(ctx context.Context, in *AllocIDRequest, opts ...grpc.CallOption) (*AllocIDResponse, error)
	UpdateChannelTimeTick(ctx context.Context, in *internalpb.ChannelTimeTickMsg, opts ...grpc.CallOption) (*commonpb.Status, error)
	ReleaseDQLMessageStream(ctx context.Context, in *proxypb.ReleaseDQLMessageStreamRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	SegmentFlushCompleted(ctx context.Context, in *datapb.SegmentFlushCompletedMsg, opts ...grpc.CallOption) (*commonpb.Status, error)
	// https://wiki.lfaidata.foundation/display/MIL/MEP+8+--+Add+metrics+for+proxy
	GetMetrics(ctx context.Context, in *milvuspb.GetMetricsRequest, opts ...grpc.CallOption) (*milvuspb.GetMetricsResponse, error)
	// https://wiki.lfaidata.foundation/display/MIL/MEP+24+--+Support+bulk+load
	Import(ctx context.Context, in *milvuspb.ImportRequest, opts ...grpc.CallOption) (*milvuspb.ImportResponse, error)
	GetImportState(ctx context.Context, in *milvuspb.GetImportStateRequest, opts ...grpc.CallOption) (*milvuspb.GetImportStateResponse, error)
	ReportImport(ctx context.Context, in *ImportResult, opts ...grpc.CallOption) (*commonpb.Status, error)
}

type rootCoordClient struct {
	cc *grpc.ClientConn
}

func NewRootCoordClient(cc *grpc.ClientConn) RootCoordClient {
	return &rootCoordClient{cc}
}

func (c *rootCoordClient) GetComponentStates(ctx context.Context, in *internalpb.GetComponentStatesRequest, opts ...grpc.CallOption) (*internalpb.ComponentStates, error) {
	out := new(internalpb.ComponentStates)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/GetComponentStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) GetTimeTickChannel(ctx context.Context, in *internalpb.GetTimeTickChannelRequest, opts ...grpc.CallOption) (*milvuspb.StringResponse, error) {
	out := new(milvuspb.StringResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/GetTimeTickChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) GetStatisticsChannel(ctx context.Context, in *internalpb.GetStatisticsChannelRequest, opts ...grpc.CallOption) (*milvuspb.StringResponse, error) {
	out := new(milvuspb.StringResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/GetStatisticsChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) CreateCollection(ctx context.Context, in *milvuspb.CreateCollectionRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/CreateCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) DropCollection(ctx context.Context, in *milvuspb.DropCollectionRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/DropCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) HasCollection(ctx context.Context, in *milvuspb.HasCollectionRequest, opts ...grpc.CallOption) (*milvuspb.BoolResponse, error) {
	out := new(milvuspb.BoolResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/HasCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) DescribeCollection(ctx context.Context, in *milvuspb.DescribeCollectionRequest, opts ...grpc.CallOption) (*milvuspb.DescribeCollectionResponse, error) {
	out := new(milvuspb.DescribeCollectionResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/DescribeCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) CreateAlias(ctx context.Context, in *milvuspb.CreateAliasRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/CreateAlias", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) DropAlias(ctx context.Context, in *milvuspb.DropAliasRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/DropAlias", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) AlterAlias(ctx context.Context, in *milvuspb.AlterAliasRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/AlterAlias", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) ShowCollections(ctx context.Context, in *milvuspb.ShowCollectionsRequest, opts ...grpc.CallOption) (*milvuspb.ShowCollectionsResponse, error) {
	out := new(milvuspb.ShowCollectionsResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/ShowCollections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) CreatePartition(ctx context.Context, in *milvuspb.CreatePartitionRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/CreatePartition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) DropPartition(ctx context.Context, in *milvuspb.DropPartitionRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/DropPartition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) HasPartition(ctx context.Context, in *milvuspb.HasPartitionRequest, opts ...grpc.CallOption) (*milvuspb.BoolResponse, error) {
	out := new(milvuspb.BoolResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/HasPartition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) ShowPartitions(ctx context.Context, in *milvuspb.ShowPartitionsRequest, opts ...grpc.CallOption) (*milvuspb.ShowPartitionsResponse, error) {
	out := new(milvuspb.ShowPartitionsResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/ShowPartitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) DescribeSegment(ctx context.Context, in *milvuspb.DescribeSegmentRequest, opts ...grpc.CallOption) (*milvuspb.DescribeSegmentResponse, error) {
	out := new(milvuspb.DescribeSegmentResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/DescribeSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) ShowSegments(ctx context.Context, in *milvuspb.ShowSegmentsRequest, opts ...grpc.CallOption) (*milvuspb.ShowSegmentsResponse, error) {
	out := new(milvuspb.ShowSegmentsResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/ShowSegments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) DescribeSegments(ctx context.Context, in *DescribeSegmentsRequest, opts ...grpc.CallOption) (*DescribeSegmentsResponse, error) {
	out := new(DescribeSegmentsResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/DescribeSegments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) CreateIndex(ctx context.Context, in *milvuspb.CreateIndexRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/CreateIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) DescribeIndex(ctx context.Context, in *milvuspb.DescribeIndexRequest, opts ...grpc.CallOption) (*milvuspb.DescribeIndexResponse, error) {
	out := new(milvuspb.DescribeIndexResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/DescribeIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) DropIndex(ctx context.Context, in *milvuspb.DropIndexRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/DropIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) AllocTimestamp(ctx context.Context, in *AllocTimestampRequest, opts ...grpc.CallOption) (*AllocTimestampResponse, error) {
	out := new(AllocTimestampResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/AllocTimestamp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) AllocID(ctx context.Context, in *AllocIDRequest, opts ...grpc.CallOption) (*AllocIDResponse, error) {
	out := new(AllocIDResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/AllocID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) UpdateChannelTimeTick(ctx context.Context, in *internalpb.ChannelTimeTickMsg, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/UpdateChannelTimeTick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) ReleaseDQLMessageStream(ctx context.Context, in *proxypb.ReleaseDQLMessageStreamRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/ReleaseDQLMessageStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) SegmentFlushCompleted(ctx context.Context, in *datapb.SegmentFlushCompletedMsg, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/SegmentFlushCompleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) GetMetrics(ctx context.Context, in *milvuspb.GetMetricsRequest, opts ...grpc.CallOption) (*milvuspb.GetMetricsResponse, error) {
	out := new(milvuspb.GetMetricsResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) Import(ctx context.Context, in *milvuspb.ImportRequest, opts ...grpc.CallOption) (*milvuspb.ImportResponse, error) {
	out := new(milvuspb.ImportResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/Import", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) GetImportState(ctx context.Context, in *milvuspb.GetImportStateRequest, opts ...grpc.CallOption) (*milvuspb.GetImportStateResponse, error) {
	out := new(milvuspb.GetImportStateResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/GetImportState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootCoordClient) ReportImport(ctx context.Context, in *ImportResult, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.proto.rootcoord.RootCoord/ReportImport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RootCoordServer is the server API for RootCoord service.
type RootCoordServer interface {
	GetComponentStates(context.Context, *internalpb.GetComponentStatesRequest) (*internalpb.ComponentStates, error)
	GetTimeTickChannel(context.Context, *internalpb.GetTimeTickChannelRequest) (*milvuspb.StringResponse, error)
	GetStatisticsChannel(context.Context, *internalpb.GetStatisticsChannelRequest) (*milvuspb.StringResponse, error)
	//*
	// @brief This method is used to create collection
	//
	// @param CreateCollectionRequest, use to provide collection information to be created.
	//
	// @return Status
	CreateCollection(context.Context, *milvuspb.CreateCollectionRequest) (*commonpb.Status, error)
	//*
	// @brief This method is used to delete collection.
	//
	// @param DropCollectionRequest, collection name is going to be deleted.
	//
	// @return Status
	DropCollection(context.Context, *milvuspb.DropCollectionRequest) (*commonpb.Status, error)
	//*
	// @brief This method is used to test collection existence.
	//
	// @param HasCollectionRequest, collection name is going to be tested.
	//
	// @return BoolResponse
	HasCollection(context.Context, *milvuspb.HasCollectionRequest) (*milvuspb.BoolResponse, error)
	//*
	// @brief This method is used to get collection schema.
	//
	// @param DescribeCollectionRequest, target collection name.
	//
	// @return CollectionSchema
	DescribeCollection(context.Context, *milvuspb.DescribeCollectionRequest) (*milvuspb.DescribeCollectionResponse, error)
	CreateAlias(context.Context, *milvuspb.CreateAliasRequest) (*commonpb.Status, error)
	DropAlias(context.Context, *milvuspb.DropAliasRequest) (*commonpb.Status, error)
	AlterAlias(context.Context, *milvuspb.AlterAliasRequest) (*commonpb.Status, error)
	//*
	// @brief This method is used to list all collections.
	//
	// @return StringListResponse, collection name list
	ShowCollections(context.Context, *milvuspb.ShowCollectionsRequest) (*milvuspb.ShowCollectionsResponse, error)
	//*
	// @brief This method is used to create partition
	//
	// @return Status
	CreatePartition(context.Context, *milvuspb.CreatePartitionRequest) (*commonpb.Status, error)
	//*
	// @brief This method is used to drop partition
	//
	// @return Status
	DropPartition(context.Context, *milvuspb.DropPartitionRequest) (*commonpb.Status, error)
	//*
	// @brief This method is used to test partition existence.
	//
	// @return BoolResponse
	HasPartition(context.Context, *milvuspb.HasPartitionRequest) (*milvuspb.BoolResponse, error)
	//*
	// @brief This method is used to show partition information
	//
	// @param ShowPartitionRequest, target collection name.
	//
	// @return StringListResponse
	ShowPartitions(context.Context, *milvuspb.ShowPartitionsRequest) (*milvuspb.ShowPartitionsResponse, error)
	DescribeSegment(context.Context, *milvuspb.DescribeSegmentRequest) (*milvuspb.DescribeSegmentResponse, error)
	ShowSegments(context.Context, *milvuspb.ShowSegmentsRequest) (*milvuspb.ShowSegmentsResponse, error)
	DescribeSegments(context.Context, *DescribeSegmentsRequest) (*DescribeSegmentsResponse, error)
	CreateIndex(context.Context, *milvuspb.CreateIndexRequest) (*commonpb.Status, error)
	DescribeIndex(context.Context, *milvuspb.DescribeIndexRequest) (*milvuspb.DescribeIndexResponse, error)
	DropIndex(context.Context, *milvuspb.DropIndexRequest) (*commonpb.Status, error)
	AllocTimestamp(context.Context, *AllocTimestampRequest) (*AllocTimestampResponse, error)
	AllocID(context.Context, *AllocIDRequest) (*AllocIDResponse, error)
	UpdateChannelTimeTick(context.Context, *internalpb.ChannelTimeTickMsg) (*commonpb.Status, error)
	ReleaseDQLMessageStream(context.Context, *proxypb.ReleaseDQLMessageStreamRequest) (*commonpb.Status, error)
	SegmentFlushCompleted(context.Context, *datapb.SegmentFlushCompletedMsg) (*commonpb.Status, error)
	// https://wiki.lfaidata.foundation/display/MIL/MEP+8+--+Add+metrics+for+proxy
	GetMetrics(context.Context, *milvuspb.GetMetricsRequest) (*milvuspb.GetMetricsResponse, error)
	// https://wiki.lfaidata.foundation/display/MIL/MEP+24+--+Support+bulk+load
	Import(context.Context, *milvuspb.ImportRequest) (*milvuspb.ImportResponse, error)
	GetImportState(context.Context, *milvuspb.GetImportStateRequest) (*milvuspb.GetImportStateResponse, error)
	ReportImport(context.Context, *ImportResult) (*commonpb.Status, error)
}

// UnimplementedRootCoordServer can be embedded to have forward compatible implementations.
type UnimplementedRootCoordServer struct {
}

func (*UnimplementedRootCoordServer) GetComponentStates(ctx context.Context, req *internalpb.GetComponentStatesRequest) (*internalpb.ComponentStates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentStates not implemented")
}
func (*UnimplementedRootCoordServer) GetTimeTickChannel(ctx context.Context, req *internalpb.GetTimeTickChannelRequest) (*milvuspb.StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeTickChannel not implemented")
}
func (*UnimplementedRootCoordServer) GetStatisticsChannel(ctx context.Context, req *internalpb.GetStatisticsChannelRequest) (*milvuspb.StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticsChannel not implemented")
}
func (*UnimplementedRootCoordServer) CreateCollection(ctx context.Context, req *milvuspb.CreateCollectionRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollection not implemented")
}
func (*UnimplementedRootCoordServer) DropCollection(ctx context.Context, req *milvuspb.DropCollectionRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropCollection not implemented")
}
func (*UnimplementedRootCoordServer) HasCollection(ctx context.Context, req *milvuspb.HasCollectionRequest) (*milvuspb.BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasCollection not implemented")
}
func (*UnimplementedRootCoordServer) DescribeCollection(ctx context.Context, req *milvuspb.DescribeCollectionRequest) (*milvuspb.DescribeCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeCollection not implemented")
}
func (*UnimplementedRootCoordServer) CreateAlias(ctx context.Context, req *milvuspb.CreateAliasRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlias not implemented")
}
func (*UnimplementedRootCoordServer) DropAlias(ctx context.Context, req *milvuspb.DropAliasRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropAlias not implemented")
}
func (*UnimplementedRootCoordServer) AlterAlias(ctx context.Context, req *milvuspb.AlterAliasRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlterAlias not implemented")
}
func (*UnimplementedRootCoordServer) ShowCollections(ctx context.Context, req *milvuspb.ShowCollectionsRequest) (*milvuspb.ShowCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowCollections not implemented")
}
func (*UnimplementedRootCoordServer) CreatePartition(ctx context.Context, req *milvuspb.CreatePartitionRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePartition not implemented")
}
func (*UnimplementedRootCoordServer) DropPartition(ctx context.Context, req *milvuspb.DropPartitionRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropPartition not implemented")
}
func (*UnimplementedRootCoordServer) HasPartition(ctx context.Context, req *milvuspb.HasPartitionRequest) (*milvuspb.BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasPartition not implemented")
}
func (*UnimplementedRootCoordServer) ShowPartitions(ctx context.Context, req *milvuspb.ShowPartitionsRequest) (*milvuspb.ShowPartitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowPartitions not implemented")
}
func (*UnimplementedRootCoordServer) DescribeSegment(ctx context.Context, req *milvuspb.DescribeSegmentRequest) (*milvuspb.DescribeSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeSegment not implemented")
}
func (*UnimplementedRootCoordServer) ShowSegments(ctx context.Context, req *milvuspb.ShowSegmentsRequest) (*milvuspb.ShowSegmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowSegments not implemented")
}
func (*UnimplementedRootCoordServer) DescribeSegments(ctx context.Context, req *DescribeSegmentsRequest) (*DescribeSegmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeSegments not implemented")
}
func (*UnimplementedRootCoordServer) CreateIndex(ctx context.Context, req *milvuspb.CreateIndexRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (*UnimplementedRootCoordServer) DescribeIndex(ctx context.Context, req *milvuspb.DescribeIndexRequest) (*milvuspb.DescribeIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeIndex not implemented")
}
func (*UnimplementedRootCoordServer) DropIndex(ctx context.Context, req *milvuspb.DropIndexRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropIndex not implemented")
}
func (*UnimplementedRootCoordServer) AllocTimestamp(ctx context.Context, req *AllocTimestampRequest) (*AllocTimestampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocTimestamp not implemented")
}
func (*UnimplementedRootCoordServer) AllocID(ctx context.Context, req *AllocIDRequest) (*AllocIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocID not implemented")
}
func (*UnimplementedRootCoordServer) UpdateChannelTimeTick(ctx context.Context, req *internalpb.ChannelTimeTickMsg) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChannelTimeTick not implemented")
}
func (*UnimplementedRootCoordServer) ReleaseDQLMessageStream(ctx context.Context, req *proxypb.ReleaseDQLMessageStreamRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseDQLMessageStream not implemented")
}
func (*UnimplementedRootCoordServer) SegmentFlushCompleted(ctx context.Context, req *datapb.SegmentFlushCompletedMsg) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SegmentFlushCompleted not implemented")
}
func (*UnimplementedRootCoordServer) GetMetrics(ctx context.Context, req *milvuspb.GetMetricsRequest) (*milvuspb.GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (*UnimplementedRootCoordServer) Import(ctx context.Context, req *milvuspb.ImportRequest) (*milvuspb.ImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Import not implemented")
}
func (*UnimplementedRootCoordServer) GetImportState(ctx context.Context, req *milvuspb.GetImportStateRequest) (*milvuspb.GetImportStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImportState not implemented")
}
func (*UnimplementedRootCoordServer) ReportImport(ctx context.Context, req *ImportResult) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportImport not implemented")
}

func RegisterRootCoordServer(s *grpc.Server, srv RootCoordServer) {
	s.RegisterService(&_RootCoord_serviceDesc, srv)
}

func _RootCoord_GetComponentStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.GetComponentStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).GetComponentStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/GetComponentStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).GetComponentStates(ctx, req.(*internalpb.GetComponentStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_GetTimeTickChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.GetTimeTickChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).GetTimeTickChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/GetTimeTickChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).GetTimeTickChannel(ctx, req.(*internalpb.GetTimeTickChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_GetStatisticsChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.GetStatisticsChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).GetStatisticsChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/GetStatisticsChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).GetStatisticsChannel(ctx, req.(*internalpb.GetStatisticsChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/CreateCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).CreateCollection(ctx, req.(*milvuspb.CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.DropCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/DropCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).DropCollection(ctx, req.(*milvuspb.DropCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_HasCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.HasCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).HasCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/HasCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).HasCollection(ctx, req.(*milvuspb.HasCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_DescribeCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.DescribeCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).DescribeCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/DescribeCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).DescribeCollection(ctx, req.(*milvuspb.DescribeCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_CreateAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.CreateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).CreateAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/CreateAlias",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).CreateAlias(ctx, req.(*milvuspb.CreateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_DropAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.DropAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).DropAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/DropAlias",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).DropAlias(ctx, req.(*milvuspb.DropAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_AlterAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.AlterAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).AlterAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/AlterAlias",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).AlterAlias(ctx, req.(*milvuspb.AlterAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_ShowCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.ShowCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).ShowCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/ShowCollections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).ShowCollections(ctx, req.(*milvuspb.ShowCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_CreatePartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.CreatePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).CreatePartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/CreatePartition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).CreatePartition(ctx, req.(*milvuspb.CreatePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_DropPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.DropPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).DropPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/DropPartition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).DropPartition(ctx, req.(*milvuspb.DropPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_HasPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.HasPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).HasPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/HasPartition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).HasPartition(ctx, req.(*milvuspb.HasPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_ShowPartitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.ShowPartitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).ShowPartitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/ShowPartitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).ShowPartitions(ctx, req.(*milvuspb.ShowPartitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_DescribeSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.DescribeSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).DescribeSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/DescribeSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).DescribeSegment(ctx, req.(*milvuspb.DescribeSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_ShowSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.ShowSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).ShowSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/ShowSegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).ShowSegments(ctx, req.(*milvuspb.ShowSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_DescribeSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).DescribeSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/DescribeSegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).DescribeSegments(ctx, req.(*DescribeSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/CreateIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).CreateIndex(ctx, req.(*milvuspb.CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_DescribeIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.DescribeIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).DescribeIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/DescribeIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).DescribeIndex(ctx, req.(*milvuspb.DescribeIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_DropIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.DropIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).DropIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/DropIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).DropIndex(ctx, req.(*milvuspb.DropIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_AllocTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).AllocTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/AllocTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).AllocTimestamp(ctx, req.(*AllocTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_AllocID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).AllocID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/AllocID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).AllocID(ctx, req.(*AllocIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_UpdateChannelTimeTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.ChannelTimeTickMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).UpdateChannelTimeTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/UpdateChannelTimeTick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).UpdateChannelTimeTick(ctx, req.(*internalpb.ChannelTimeTickMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_ReleaseDQLMessageStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proxypb.ReleaseDQLMessageStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).ReleaseDQLMessageStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/ReleaseDQLMessageStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).ReleaseDQLMessageStream(ctx, req.(*proxypb.ReleaseDQLMessageStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_SegmentFlushCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(datapb.SegmentFlushCompletedMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).SegmentFlushCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/SegmentFlushCompleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).SegmentFlushCompleted(ctx, req.(*datapb.SegmentFlushCompletedMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).GetMetrics(ctx, req.(*milvuspb.GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_Import_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).Import(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/Import",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).Import(ctx, req.(*milvuspb.ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_GetImportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.GetImportStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).GetImportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/GetImportState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).GetImportState(ctx, req.(*milvuspb.GetImportStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootCoord_ReportImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootCoordServer).ReportImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.rootcoord.RootCoord/ReportImport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootCoordServer).ReportImport(ctx, req.(*ImportResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _RootCoord_serviceDesc = grpc.ServiceDesc{
	ServiceName: "milvus.proto.rootcoord.RootCoord",
	HandlerType: (*RootCoordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetComponentStates",
			Handler:    _RootCoord_GetComponentStates_Handler,
		},
		{
			MethodName: "GetTimeTickChannel",
			Handler:    _RootCoord_GetTimeTickChannel_Handler,
		},
		{
			MethodName: "GetStatisticsChannel",
			Handler:    _RootCoord_GetStatisticsChannel_Handler,
		},
		{
			MethodName: "CreateCollection",
			Handler:    _RootCoord_CreateCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _RootCoord_DropCollection_Handler,
		},
		{
			MethodName: "HasCollection",
			Handler:    _RootCoord_HasCollection_Handler,
		},
		{
			MethodName: "DescribeCollection",
			Handler:    _RootCoord_DescribeCollection_Handler,
		},
		{
			MethodName: "CreateAlias",
			Handler:    _RootCoord_CreateAlias_Handler,
		},
		{
			MethodName: "DropAlias",
			Handler:    _RootCoord_DropAlias_Handler,
		},
		{
			MethodName: "AlterAlias",
			Handler:    _RootCoord_AlterAlias_Handler,
		},
		{
			MethodName: "ShowCollections",
			Handler:    _RootCoord_ShowCollections_Handler,
		},
		{
			MethodName: "CreatePartition",
			Handler:    _RootCoord_CreatePartition_Handler,
		},
		{
			MethodName: "DropPartition",
			Handler:    _RootCoord_DropPartition_Handler,
		},
		{
			MethodName: "HasPartition",
			Handler:    _RootCoord_HasPartition_Handler,
		},
		{
			MethodName: "ShowPartitions",
			Handler:    _RootCoord_ShowPartitions_Handler,
		},
		{
			MethodName: "DescribeSegment",
			Handler:    _RootCoord_DescribeSegment_Handler,
		},
		{
			MethodName: "ShowSegments",
			Handler:    _RootCoord_ShowSegments_Handler,
		},
		{
			MethodName: "DescribeSegments",
			Handler:    _RootCoord_DescribeSegments_Handler,
		},
		{
			MethodName: "CreateIndex",
			Handler:    _RootCoord_CreateIndex_Handler,
		},
		{
			MethodName: "DescribeIndex",
			Handler:    _RootCoord_DescribeIndex_Handler,
		},
		{
			MethodName: "DropIndex",
			Handler:    _RootCoord_DropIndex_Handler,
		},
		{
			MethodName: "AllocTimestamp",
			Handler:    _RootCoord_AllocTimestamp_Handler,
		},
		{
			MethodName: "AllocID",
			Handler:    _RootCoord_AllocID_Handler,
		},
		{
			MethodName: "UpdateChannelTimeTick",
			Handler:    _RootCoord_UpdateChannelTimeTick_Handler,
		},
		{
			MethodName: "ReleaseDQLMessageStream",
			Handler:    _RootCoord_ReleaseDQLMessageStream_Handler,
		},
		{
			MethodName: "SegmentFlushCompleted",
			Handler:    _RootCoord_SegmentFlushCompleted_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _RootCoord_GetMetrics_Handler,
		},
		{
			MethodName: "Import",
			Handler:    _RootCoord_Import_Handler,
		},
		{
			MethodName: "GetImportState",
			Handler:    _RootCoord_GetImportState_Handler,
		},
		{
			MethodName: "ReportImport",
			Handler:    _RootCoord_ReportImport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "root_coord.proto",
}
